#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

blog_list:
    path:       /blog/{page}
    controller: App\Controller\BlogController::list
    requirements:
        page: '\d+'

blog_show:
    path:       /blog/{slug}
    controller: App\Controller\BlogController::show
